### PR TITLE
chore(lodash): remove isNaN

### PR DESCRIPTION
**Pull request by Haroenv**
_.isNaN behaves like Number.isNaN according to the docs: https://lodash.com/docs#isNaN

and Number.isNaN is supported where we want it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

Also a really small impact, but quickly saw it while researching the isArray situation

### CODE REVIEW

**Comment by samouss** [comment]
`Number.isNaN` is not supported on IE.

**Comment by bobylito** [comment]
> Number.isNaN is not supported on IE.

but the support can be provided by polyfill.io https://polyfill.io/v2/docs/features/

**Comment by Haroenv** [comment]
oh, I misread the support table and saw the `yes` for edge..., package is really small so I'm not sure if it's worth for now

**Comment by bobylito** [comment]
> oh, I misread the support table and saw the yes for edge..., package is really small so I'm not sure if it's worth for now

Ok let's close for now. Thanks for taking the time.

**Pull request closed without merging**
