### PR TITLE
doc(params): Add filters to query parameters

### LINKED ISSUE #528: Documentation doesn't list "filters" as a parameter for method "setQueryParameter"
I had a moderately complex numeric filter requirement and couldn't find any way to do it with the search helper. After contacting Algolia technical support, I was informed of `searchHelper.setQueryParameter('filters', '...')`

I know it's in the API documentation (which is becoming increasingly difficult to find with the new site layout) but it's very difficult to connect the dots when the documentation makes it seems as though everything that can be done is listed.

### PR DESCRIPTION
**Pull request by julienbourdeau**
fix #528 

In case this table was autogenerated from somewhere else, feel free to close this PR.

### CODE REVIEW

**Comment by Haroenv** [comment]
I'd rather remove the whole table and link the doc instead. WDYT @bobylito?

**Comment by julienbourdeau** [comment]
Agreed 💯

**Comment by bobylito** [comment]
I think it's the best option too @haroenv 👍👍

**Comment by bobylito** [comment]
We might want to update the website too actually. But as far as this pr is concerned, removing the table and providing the link is enough, no?

**Pull request merged**
