### PR TITLE
chore(shortener): Sort key names alphabetically

### PR DESCRIPTION
**Pull request by pixelastic**
Just a sorting of the shortener keys alphabetically. Makes searching for an attribute easier and will make diffs cleaner.

### CODE REVIEW

**Comment by bobylito** [comment]
LGTM

**Comment by vvo** [comment]
Is this linked with the instantsearch issue about keeping the same order than what was defined in filters:[]?

**Comment by bobylito** [comment]
No :)

**Comment by pixelastic** [comment]
Nope, I just had to look at this file to choose a key that wasn't used for the current instantsearch.js version that is now stored in the url. I just applied the boy-scout rule here (_leave the code better than you found it_)

**Pull request merged**
