### PR TITLE
FIX #124 : Merge the cheat sheet in the readme

### LINKED ISSUE #124: Merge readme and cheat sheet

### PR DESCRIPTION
**Pull request by bobylito**
In order to have a respectful README that can actually be of some help to people.

### CODE REVIEW

**Comment by vvo** [comment]
Cool, only missing part is following the eslint style

**Comment by redox** [comment]
Looks good :+1:

**Comment by bobylito** [comment]
I've udpated the coding style but this one doesn't compile either :/

**Comment by vvo** [comment]
amazing, almost nothing changed

**Comment by vvo** [comment]
I suspect travis having issues.. let's merge this

**Comment by vvo** [comment]
It's not even a saucelabs issue it's just that travis seems to not decode the encrypted variables

**Pull request merged**
