### PR TITLE
docs(jsdoc): fix spelling

### PR DESCRIPTION
**Pull request by Haroenv**
I have spelling detection enabled in my editor, and it complained that there were a few typos, so I fixed them.

There's one typo I can't really fix or I'm not sure if it's worth it since it changes a parameter.

There's `...Sizefor...` in a few attributes that should be `...SizeFor...`.

### CODE REVIEW

**Comment by Haroenv** [comment]
Just ran the test locally, and it passes (wow just 4 seconds for such a huge codebase, props!) Since I didn’t change code, it’s probably okay anyway 😄

**Comment by bobylito** [comment]
You're right let's merge. From what I've seen in the debug I would say there is a problem with phantom js and node 8 :/

**Comment by Haroenv** [comment]
@bobylito, I think @vvo pinned the version to node 7 in instantsearch.js, maybe the same?

**Comment by bobylito** [comment]
Maybe :)

**Comment by vvo** [comment]
Yes, easiest is to:

remove version or stable from travis.yml,
put specific version in package.json and nvmrc.

See https://github.com/algolia/react-instantsearch/commit/afc1b2f7e21bbddedc64df70cf5578f3bb95cbf6

Node V8 is very new and some packages might not be installable for now.

**Pull request merged**
