### PR TITLE
doc(places): Remove/replace references to Algolia Places

### PR DESCRIPTION
**Pull request by pixelastic**
Mostly this is changing the `utm` in the footer to a specific one for
the Helper, not Algolia places.

Also removed some legacy CSS from the Places website.

### CODE REVIEW

**Comment by Haroenv** [comment]
can you run `npm run doc:staging`?

**Comment by pixelastic** [comment]
Actually no. `surge not found`.
Should I add it to `package.json` and create a surge account?

**Comment by bobylito** [comment]
Yes you need to create a surge account for this. However let me have a look.

**Comment by bobylito** [comment]
I will stage it!

**Comment by bobylito** [comment]
http://extra-small-insurance.surge.sh/

**Pull request merged**
