### PR TITLE
fix(hierarchical): refined + no result

### PR DESCRIPTION
**Pull request by maxiloc**

### CODE REVIEW

**Comment by maxiloc** [comment]
@vvo Not sure how to test this one

**Comment by vvo** [comment]
Can you elaborate on what you are fixing with maybe a list of actions leading to the bug (this will help build the test case)

**Comment by maxiloc** [comment]
If you refine the hierarchical menu and then type a query that lead to no results.
https://github.com/algolia/instantsearch.js/issues/385

**Comment by vvo** [comment]
So you could start with simple.js again and make it so you have two actions (first toggle where you have results, then do a new search where there are no results).

Or did you already tried so?

**Comment by maxiloc** [comment]
Yes that's ok, I am just not sure what to assert

**Comment by vvo** [comment]
You should assert on the output of getFacetValues I guess?

**Comment by maxiloc** [comment]
@vvo I think it's good to go

**Comment by vvo** [comment]
:clap:

**Pull request merged**
