### PR TITLE
feat: IE8 compatibility

### PR DESCRIPTION
**Pull request by vvo**
we automatically switch to lodash-compat when building for browsers.
Thus having a lodash IE8 compatible module.

+ some adjustments
+ activate IE8 testing

### CODE REVIEW

**Comment by vvo** [comment]
cc @bobylito @redox 

Not so much changes needed

**Comment by vvo** [comment]
The IE8 travis test will be done when merged on develop, but I launched it locally, it's ok

**Comment by redox** [comment]
LGTM :+1:

**Comment by bobylito** [comment]
Nice !! Some ie 8 love ;)
:+1: LGTM

**Comment by vvo** [comment]
Happy hour merge!

**Pull request merged**
