### PR TITLE
FIX #12 Add a method to get any parameter of the search

### LINKED ISSUE #12: Setters/getters for misc parameters
Add functions to set and get the value for any parameters that will be used for the the search.

### PR DESCRIPTION
**Pull request by bobylito**
Fix for #12

### CODE REVIEW

**Comment by redox** [comment]
LGTM :+1:

**Comment by redox** [comment]
Oh wait

**Comment by redox** [comment]
LGTM :+1:  :)

**Comment by bobylito** [comment]
Thanks for the feedback @redox !

**Pull request merged**
