### PR TITLE
docs(instantiate): use existing signature of toggleRefine

### PR DESCRIPTION
**Pull request by Haroenv**
The way this was documented throws an error

see https://codesandbox.io/s/o7k7w28n86

### CODE REVIEW

**Comment by samouss** [comment]
Yes it's because it's deprecated we should avoid to document this usage.

https://github.com/algolia/algoliasearch-helper-js/blob/fa4a93d94537f1416564408a972556cf43478958/src/algoliasearch.helper.js#L656-L660

**Comment by francoischalifour** [comment]
@samouss Here we're even talking about `toggeRefine()` (not `toggleRefinement()`).

**Comment by Haroenv** [comment]
good point, let's move this to a one that's actually correct

**Comment by samouss** [comment]
I've updated the code, it's still deprecated.

**Pull request merged**
