### PR TITLE
Fix #112 : do not set undefined to distinct in the request.

### LINKED ISSUE #112: distinct=undefined is sent to the API if distinct is not set
distinct=undefined is sent to the API if distinct is not set, generating a 400 error.

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by bobylito** [comment]
On hold : will find a test for this specific case.

**Comment by redox** [comment]
LGTM :+1:

**Comment by bobylito** [comment]
Modified the tests @vvo :)

**Comment by vvo** [comment]
good :dancer: LGTM

**Comment by bobylito** [comment]
Thanks!

**Pull request merged**
